// updated 21/01/2022

const fallback = {
  "12 Gauge Shot": [
    {
      name: "5.25mm Buckshot",
      damage: "37",
      penValue: "1",
      fragChange: "0%",
      recoil: "",
      effDist: "108",
      maxHsDist: "9",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
      standard: {
        name: "12/70 5.25mm buckshot",
        normalizedName: "1270-525mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: '8.5mm Buckshot "Magnum"',
      damage: "50",
      penValue: "2",
      fragChange: "0%",
      recoil: "155",
      effDist: "80",
      maxHsDist: "116",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
      standard: {
        name: "12/70 8.5mm Magnum buckshot",
        normalizedName: "1270-85mm-magnum-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: '6.5mm Buckshot "Express"',
      damage: "35",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "71",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
      category: "12 Gauge Shot",
      standard: {
        name: "12/70 6.5mm Express buckshot",
        normalizedName: "1270-65mm-express-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "7mm Buckshot",
      damage: "39",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "39",
      maxHsDist: "3",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "12 Gauge Shot",
      standard: {
        name: "12/70 7mm buckshot",
        normalizedName: "1270-7mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Flechette",
      damage: "25",
      penValue: "31",
      fragChange: "0%",
      recoil: "",
      effDist: "1185",
      maxHsDist: "Never",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "5",
      class6: "5",
      note: "8 Darts, the armor damage is pretty high per dart and with 8 total darts, it destroys armor very quickly",
      category: "12 Gauge Shot",
      standard: { name: "12/70 flechette", normalizedName: "1270-flechette" },
      notAvailableOnFleaMarket: false
    }
  ],
  "12 Gauge Slugs": [
    {
      name: "RIP Slug",
      damage: "265",
      penValue: "2",
      fragChange: "100%",
      recoil: "35",
      effDist: "188",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "Because it has less than 20 pen, even though it has a 100% fragment chance, it can't fragment",
      category: "12 Gauge Slugs",
      standard: { name: "12/70 RIP", normalizedName: "1270-rip" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Superformance HP Slug",
      damage: "220",
      penValue: "5",
      fragChange: "39%",
      recoil: "-15",
      effDist: "344",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "^ This is true of all ammo under 20 pen",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 SuperFormance HP slug",
        normalizedName: "1270-superformance-hp-slug"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "Grizzly 40 Slug",
      damage: "190",
      penValue: "12",
      fragChange: "12%",
      recoil: "20",
      effDist: "840",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 Grizzly 40 slug",
        normalizedName: "1270-grizzly-40-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Copper Sabot Premier HP",
      damage: "206",
      penValue: "14",
      fragChange: "38%",
      recoil: "10",
      effDist: "305",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 Copper Sabot Premier HP slug",
        normalizedName: "1270-copper-sabot-premier-hp-slug"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "Lead Slug",
      damage: "167",
      penValue: "15",
      fragChange: "20%",
      recoil: "",
      effDist: "487",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: { name: "12/70 lead slug", normalizedName: "1270-lead-slug" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Dual Sabot Slug",
      damage: "85",
      penValue: "17",
      fragChange: "10%",
      recoil: "15",
      effDist: "251",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "2 Slugs",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 Dual Sabot slug",
        normalizedName: "1270-dual-sabot-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "140",
      penValue: "17",
      fragChange: "20%",
      recoil: "-15",
      effDist: "406",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: '12/70 \\"Poleva-3\\" slug',
        normalizedName: "1270-poleva-3-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FTX Custom Lite Slug",
      damage: "183",
      penValue: "20",
      fragChange: "10%",
      recoil: "-25",
      effDist: "498",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 FTX Custom Lite slug",
        normalizedName: "1270-ftx-custom-lite-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "150",
      penValue: "20",
      fragChange: "15%",
      recoil: "-10",
      effDist: "181",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: '12/70 \\"Poleva-6u\\" slug',
        normalizedName: "1270-poleva-6u-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Shell With .50 BMG (Tracer)",
      damage: "197",
      penValue: "26",
      fragChange: "5%",
      recoil: "25",
      effDist: "2058",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 makeshift .50 BMG slug",
        normalizedName: "1270-makeshift-50-bmg-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "AP 20 Slug",
      damage: "164",
      penValue: "37",
      fragChange: "3%",
      recoil: "50",
      effDist: "905",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "12 Gauge Slugs",
      standard: {
        name: "12/70 AP-20 armor-piercing slug",
        normalizedName: "1270-ap-20-armor-piercing-slug"
      },
      notAvailableOnFleaMarket: true
    }
  ],
  "20 Gauge": [
    {
      name: "5.6mm Buckshot",
      damage: "26",
      penValue: "1",
      fragChange: "0%",
      recoil: "10",
      effDist: "124",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
      standard: {
        name: "20/70 5.6mm buckshot",
        normalizedName: "2070-56mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "6.2mm Buckshot",
      damage: "22",
      penValue: "2",
      fragChange: "0%",
      recoil: "",
      effDist: "100",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
      standard: {
        name: "20/70 6.2mm buckshot",
        normalizedName: "2070-62mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "7.5mm Buckshot",
      damage: "25",
      penValue: "3",
      fragChange: "0%",
      recoil: "",
      effDist: "181",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "20 Gauge",
      standard: {
        name: "20/70 7.5mm buckshot",
        normalizedName: "2070-75mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "7.3mm Buckshot",
      damage: "23",
      penValue: "3",
      fragChange: "0%",
      recoil: "15",
      effDist: "86",
      maxHsDist: "Never",
      class1: "3",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "9 Pellets",
      category: "20 Gauge",
      standard: {
        name: "20/70 7.3mm buckshot",
        normalizedName: "2070-73mm-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Devastator Slug",
      damage: "198",
      penValue: "5",
      fragChange: "100%",
      recoil: "30",
      effDist: "109",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
      standard: {
        name: "20/70 Devastator slug",
        normalizedName: "2070-devastator-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: 'Slug "Poleva-3"',
      damage: "120",
      penValue: "14",
      fragChange: "20%",
      recoil: "-15",
      effDist: "517",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
      standard: {
        name: '20/70 \\"Poleva-3\\" slug',
        normalizedName: "2070-poleva-3-slug"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Star Slug",
      damage: "154",
      penValue: "16",
      fragChange: "10%",
      recoil: "5",
      effDist: "416",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
      standard: { name: "20/70 Star slug", normalizedName: "2070-star-slug" },
      notAvailableOnFleaMarket: false
    },
    {
      name: 'Slug "Poleva-6u" ',
      damage: "135",
      penValue: "17",
      fragChange: "15%",
      recoil: "-10",
      effDist: "438",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "20 Gauge",
      standard: {
        name: '20/70 \\"Poleva-6u\\" slug',
        normalizedName: "2070-poleva-6u-slug"
      },
      notAvailableOnFleaMarket: false
    }
  ],
  "23x75 mm": [
    {
      name: '"Star" Flashbang Slug',
      damage: "0",
      penValue: "0",
      fragChange: "20%",
      recoil: "",
      effDist: "",
      maxHsDist: "",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "23x75 mm",
      standard: {
        name: '23x75mm \\"Zvezda\\" flashbang round',
        normalizedName: "23x75mm-zvezda-flashbang-round"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "Shrapnel 25",
      damage: "78",
      penValue: "10",
      fragChange: "0%",
      recoil: "10",
      effDist: "83",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "23x75 mm",
      standard: {
        name: '23x75mm \\"Shrapnel-25\\" buckshot',
        normalizedName: "23x75mm-shrapnel-25-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Shrapnel 10",
      damage: "87",
      penValue: "11",
      fragChange: "0%",
      recoil: "",
      effDist: "106",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "8 Pellets",
      category: "23x75 mm",
      standard: {
        name: '23x75mm \\"Shrapnel-10\\" buckshot',
        normalizedName: "23x75mm-shrapnel-10-buckshot"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: '"Barricade" Slug',
      damage: "192",
      penValue: "39",
      fragChange: "20%",
      recoil: "25",
      effDist: "974",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "4",
      category: "23x75 mm",
      standard: {
        name: '23x75mm \\"Barrikada\\" slug',
        normalizedName: "23x75mm-barrikada-slug"
      },
      notAvailableOnFleaMarket: false
    }
  ],
  "9x18mm": [
    {
      name: "SP8",
      damage: "67",
      penValue: "1",
      fragChange: "60%",
      recoil: "",
      effDist: "412",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM SP8 gzh",
        normalizedName: "9x18mm-pm-sp8-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "SP7",
      damage: "77",
      penValue: "2",
      fragChange: "2%",
      recoil: "",
      effDist: "229",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM SP7 gzh",
        normalizedName: "9x18mm-pm-sp7-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PSV",
      damage: "69",
      penValue: "3",
      fragChange: "40%",
      recoil: "",
      effDist: "606",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: { name: "9x18mm PM PSV", normalizedName: "9x18mm-pm-psv" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "P gzh",
      damage: "50",
      penValue: "5",
      fragChange: "25%",
      recoil: "",
      effDist: "478",
      maxHsDist: "638",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: { name: "9x18mm PM P gzh", normalizedName: "9x18mm-pm-p-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PSO gzh",
      damage: "54",
      penValue: "5",
      fragChange: "35%",
      recoil: "",
      effDist: "459",
      maxHsDist: "818",
      class1: "2",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM PSO gzh",
        normalizedName: "9x18mm-pm-pso-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PS gs PPO",
      damage: "55",
      penValue: "6",
      fragChange: "25%",
      recoil: "",
      effDist: "467",
      maxHsDist: "905",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM PS gs PPO",
        normalizedName: "9x18mm-pm-ps-gs-ppo"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PRS gs",
      damage: "58",
      penValue: "6",
      fragChange: "30%",
      recoil: "",
      effDist: "478",
      maxHsDist: ">1KM",
      class1: "3",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM PRS gs",
        normalizedName: "9x18mm-pm-prs-gs"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PPE gzh",
      damage: "61",
      penValue: "7",
      fragChange: "35%",
      recoil: "",
      effDist: "438",
      maxHsDist: ">1KM",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM Ppe gzh",
        normalizedName: "9x18mm-pm-ppe-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PPT gzh",
      damage: "59",
      penValue: "8",
      fragChange: "17%",
      recoil: "-7",
      effDist: "495",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM PPT gzh",
        normalizedName: "9x18mm-pm-ppt-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PST gzh",
      damage: "50",
      penValue: "12",
      fragChange: "20%",
      recoil: "",
      effDist: "462",
      maxHsDist: "615",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM Pst gzh",
        normalizedName: "9x18mm-pm-pst-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "RG028 gzh",
      damage: "65",
      penValue: "13",
      fragChange: "2%",
      recoil: "",
      effDist: "476",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM RG028 gzh",
        normalizedName: "9x18mm-pm-rg028-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BZT gzh",
      damage: "53",
      penValue: "18",
      fragChange: "17%",
      recoil: "",
      effDist: "303",
      maxHsDist: "511",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM BZhT gzh",
        normalizedName: "9x18mm-pm-bzht-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PMM",
      damage: "58",
      penValue: "24",
      fragChange: "17%",
      recoil: "5",
      effDist: "322",
      maxHsDist: "919",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x18mm",
      standard: {
        name: "9x18mm PMM PstM gzh",
        normalizedName: "9x18mm-pmm-pstm-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PBM",
      damage: "40",
      penValue: "28",
      fragChange: "16%",
      recoil: "4",
      effDist: "133",
      maxHsDist: "26",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "1",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "290",
      category: "9x18mm",
      standard: {
        name: "9x18mm PM PBM gzh",
        normalizedName: "9x18mm-pm-pbm-gzh"
      },
      notAvailableOnFleaMarket: false
    }
  ],
  "7.62x25mm": [
    {
      name: "LRNPC",
      damage: "66",
      penValue: "7",
      fragChange: "35%",
      recoil: "-10",
      effDist: "457",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "725",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT LRNPC",
        normalizedName: "762x25mm-tt-lrnpc"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "LRN",
      damage: "64",
      penValue: "8",
      fragChange: "35%",
      recoil: "-5",
      effDist: "579",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "575",
      category: "7.62x25mm",
      standard: { name: "7.62x25mm TT LRN", normalizedName: "762x25mm-tt-lrn" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ43",
      damage: "60",
      penValue: "11",
      fragChange: "25%",
      recoil: "",
      effDist: "175",
      maxHsDist: "595",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "441",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT FMJ43",
        normalizedName: "762x25mm-tt-fmj43"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "akbs",
      damage: "58",
      penValue: "12",
      fragChange: "25%",
      recoil: "-15",
      effDist: "419",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "428",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT AKBS",
        normalizedName: "762x25mm-tt-akbs"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "P Gl",
      damage: "58",
      penValue: "14",
      fragChange: "25%",
      recoil: "",
      effDist: "411",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "194",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT P gl",
        normalizedName: "762x25mm-tt-p-gl"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "T Gzh (Tracer)",
      damage: "55",
      penValue: "18",
      fragChange: "17%",
      recoil: "",
      effDist: "426",
      maxHsDist: "966",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "453",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT PT gzh",
        normalizedName: "762x25mm-tt-pt-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Pst gzh",
      damage: "50",
      penValue: "25",
      fragChange: "20%",
      recoil: "",
      effDist: "408",
      maxHsDist: "615",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "92",
      category: "7.62x25mm",
      standard: {
        name: "7.62x25mm TT Pst gzh",
        normalizedName: "762x25mm-tt-pst-gzh"
      },
      notAvailableOnFleaMarket: false
    }
  ],
  "9x19mm": [
    {
      name: "RIP",
      damage: "102",
      penValue: "2",
      fragChange: "100%",
      recoil: "20",
      effDist: "290",
      maxHsDist: ">1KM",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
      standard: { name: "9x19mm RIP", normalizedName: "9x19mm-rip" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Quakemaker",
      damage: "85",
      penValue: "8",
      fragChange: "10%",
      recoil: "10",
      effDist: "725",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
      standard: {
        name: "9x19mm QuakeMaker",
        normalizedName: "9x19mm-quakemaker"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PSO gzh",
      damage: "59",
      penValue: "10",
      fragChange: "25%",
      recoil: "",
      effDist: "575",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
      standard: { name: "9x19mm PSO gzh", normalizedName: "9x19mm-pso-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Luger CCI",
      damage: "70",
      penValue: "10",
      fragChange: "25%",
      recoil: "",
      effDist: "441",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
      standard: {
        name: "9x19mm Luger CCI",
        normalizedName: "9x19mm-luger-cci"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "T Gzh (Tracer)",
      damage: "58",
      penValue: "14",
      fragChange: "15%",
      recoil: "-6",
      effDist: "428",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Green Tracer",
      category: "9x19mm",
      standard: { name: "9x19mm T gzh", normalizedName: "9x19mm-t-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PST gzh",
      damage: "54",
      penValue: "20",
      fragChange: "15%",
      recoil: "",
      effDist: "194",
      maxHsDist: "452",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "9x19mm",
      standard: { name: "9x19mm Pst gzh", normalizedName: "9x19mm-pst-gzh" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "AP 6.3",
      damage: "52",
      penValue: "30",
      fragChange: "5%",
      recoil: "",
      effDist: "453",
      maxHsDist: "776",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "1",
      category: "9x19mm",
      standard: { name: "9x19mm AP 6.3", normalizedName: "9x19mm-ap-63" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "PBP",
      damage: "52",
      penValue: "39",
      fragChange: "5%",
      recoil: "15",
      effDist: "92",
      maxHsDist: "220",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously 7n31",
      category: "9x19mm",
      standard: { name: "9x19mm PBP gzh", normalizedName: "9x19mm-pbp-gzh" },
      notAvailableOnFleaMarket: true
    }
  ],
  ".45": [
    {
      name: "RIP",
      damage: "137",
      penValue: "3",
      fragChange: "100%",
      recoil: "",
      effDist: "290",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
      standard: { name: ".45 ACP RIP", normalizedName: "45-acp-rip" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Hydroshok",
      damage: "105",
      penValue: "13",
      fragChange: "50%",
      recoil: "",
      effDist: "725",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
      standard: {
        name: ".45 ACP Hydra-Shok",
        normalizedName: "45-acp-hydra-shok"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Lasermatch (Tracer)",
      damage: "80",
      penValue: "19",
      fragChange: "1%",
      recoil: "",
      effDist: "575",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".45",
      standard: {
        name: ".45 ACP Lasermatch FMJ",
        normalizedName: "45-acp-lasermatch-fmj"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ACP FMJ",
      damage: "76",
      penValue: "25",
      fragChange: "1%",
      recoil: "",
      effDist: "441",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".45",
      standard: {
        name: ".45 ACP Match FMJ",
        normalizedName: "45-acp-match-fmj"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ACP AP",
      damage: "70",
      penValue: "38",
      fragChange: "1%",
      recoil: "7",
      effDist: "428",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".45",
      standard: { name: ".45 ACP AP", normalizedName: "45-acp-ap" },
      notAvailableOnFleaMarket: true
    }
  ],
  "9x21mm": [
    {
      name: "PE Gzh",
      damage: "80",
      penValue: "15",
      fragChange: "35%",
      recoil: "",
      effDist: "194",
      maxHsDist: "452",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-12",
      category: "9x21mm",
      standard: { name: "9x21mm PE gzh", normalizedName: "9x21mm-pe-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "P Gzh",
      damage: "65",
      penValue: "18",
      fragChange: "30%",
      recoil: "",
      effDist: "453",
      maxHsDist: "776",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously SP-11",
      category: "9x21mm",
      standard: { name: "9x21mm P gzh", normalizedName: "9x21mm-p-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PS Gzh",
      damage: "49",
      penValue: "35",
      fragChange: "20%",
      recoil: "",
      effDist: "92",
      maxHsDist: "220",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      note: "",
      secondNote: "Previously SP-10",
      category: "9x21mm",
      standard: { name: "9x21mm PS gzh", normalizedName: "9x21mm-ps-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BT (Tracer)",
      damage: "63",
      penValue: "39",
      fragChange: "20%",
      recoil: "-4",
      effDist: "292",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      note: "",
      secondNote: "Previously SP-13",
      category: "9x21mm",
      standard: { name: "x21mm BT gzh", normalizedName: "9x21mm-bt-gzh" },
      notAvailableOnFleaMarket: false
    }
  ],
  "5.7x28 mm": [
    {
      name: "r37f",
      damage: "98",
      penValue: "8",
      fragChange: "100%",
      recoil: "",
      effDist: "100",
      maxHsDist: ">1KM",
      class1: "4",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm R37.F", normalizedName: "57x28mm-r37f" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ss198lf",
      damage: "74",
      penValue: "10",
      fragChange: "80%",
      recoil: "",
      effDist: "326",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm SS198LF", normalizedName: "57x28mm-ss198lf" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "r37x",
      damage: "81",
      penValue: "11",
      fragChange: "70%",
      recoil: "",
      effDist: "100",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm R37.X", normalizedName: "57x28mm-r37x" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ss197sr",
      damage: "62",
      penValue: "20",
      fragChange: "50%",
      recoil: "",
      effDist: "401",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm SS197SR", normalizedName: "57x28mm-ss197sr" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "l191 (Tracer)",
      damage: "58",
      penValue: "33",
      fragChange: "20%",
      recoil: "",
      effDist: "358",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "2",
      class6: "2",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm L191", normalizedName: "57x28mm-l191" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "sb193",
      damage: "54",
      penValue: "35",
      fragChange: "20%",
      recoil: "-24",
      effDist: "1113",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm SB193", normalizedName: "57x28mm-sb193" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ss190",
      damage: "49",
      penValue: "37",
      fragChange: "20%",
      recoil: "",
      effDist: "325",
      maxHsDist: "463",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.7x28 mm",
      standard: { name: "5.7x28mm SS190", normalizedName: "57x28mm-ss190" },
      notAvailableOnFleaMarket: true
    }
  ],
  "4.6x30 mm": [
    {
      name: "Action SX",
      damage: "65",
      penValue: "18",
      fragChange: "50%",
      recoil: "",
      effDist: "245",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "4.6x30 mm",
      standard: {
        name: "4.6x30mm Action SX",
        normalizedName: "46x30mm-action-sx"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Subsonic SX",
      damage: "45",
      penValue: "36",
      fragChange: "20%",
      recoil: "-22",
      effDist: "2119",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "3",
      class6: "2",
      category: "4.6x30 mm",
      standard: {
        name: "4.6x30mm Subsonic SX",
        normalizedName: "46x30mm-subsonic-sx"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "FMJ SX",
      damage: "43",
      penValue: "40",
      fragChange: "20%",
      recoil: "",
      effDist: "367",
      maxHsDist: "189",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "4.6x30 mm",
      standard: { name: "4.6x30mm FMJ SX", normalizedName: "46x30mm-fmj-sx" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "AP SX",
      damage: "35",
      penValue: "53",
      fragChange: "10%",
      recoil: "10",
      effDist: "198",
      maxHsDist: "Never",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "4.6x30 mm",
      standard: { name: "4.6x30mm AP SX", normalizedName: "46x30mm-ap-sx" },
      notAvailableOnFleaMarket: true
    }
  ],
  "9x39mm": [
    {
      name: "SP5",
      damage: "68",
      penValue: "38",
      fragChange: "20%",
      recoil: "",
      effDist: "1710",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "9x39mm",
      standard: { name: "9x39mm SP-5 gs", normalizedName: "9x39mm-sp-5-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "SP6",
      damage: "58",
      penValue: "46",
      fragChange: "10%",
      recoil: "10",
      effDist: "1963",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "9x39mm",
      standard: { name: "9x39mm SP-6 gs", normalizedName: "9x39mm-sp-6-gs" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "PAB9",
      damage: "62",
      penValue: "48",
      fragChange: "10%",
      recoil: "10",
      effDist: "1823",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
      standard: { name: "9x39mm PAB-9 gs", normalizedName: "9x39mm-pab-9-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "SPP",
      damage: "64",
      penValue: "50",
      fragChange: "20%",
      recoil: "20",
      effDist: "887",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
      standard: { name: "9x39mm SPP gs", normalizedName: "9x39mm-spp-gs" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "BP",
      damage: "60",
      penValue: "55",
      fragChange: "10%",
      recoil: "22",
      effDist: "1902",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "9x39mm",
      standard: { name: "9x39mm BP gs", normalizedName: "9x39mm-bp-gs" },
      notAvailableOnFleaMarket: true
    }
  ],
  ".366": [
    {
      name: "Geksa",
      damage: "110",
      penValue: "14",
      fragChange: "45%",
      recoil: "",
      effDist: "484",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: ".366",
      standard: { name: ".366 TKM Geksa", normalizedName: "366-tkm-geksa" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ",
      damage: "98",
      penValue: "23",
      fragChange: "25%",
      recoil: "10",
      effDist: "363",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".366",
      standard: { name: ".366 TKM FMJ", normalizedName: "366-tkm-fmj" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "EKO",
      damage: "73",
      penValue: "30",
      fragChange: "20%",
      recoil: "-15",
      effDist: "184",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
      category: ".366",
      standard: { name: ".366 TKM EKO", normalizedName: "366-tkm-eko" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "AP",
      damage: "90",
      penValue: "42",
      fragChange: "1%",
      recoil: "35",
      effDist: "633",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: ".366",
      standard: { name: ".366 TKM AP-M", normalizedName: "366-tkm-ap-m" },
      notAvailableOnFleaMarket: false
    }
  ],
  "5.45x39 mm": [
    {
      name: "SP",
      damage: "68",
      penValue: "11",
      fragChange: "45%",
      recoil: "-15",
      effDist: "364",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm SP", normalizedName: "545x39mm-sp" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "HP",
      damage: "74",
      penValue: "11",
      fragChange: "35%",
      recoil: "5",
      effDist: "368",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "1",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm HP", normalizedName: "545x39mm-hp" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PRS",
      damage: "60",
      penValue: "14",
      fragChange: "30%",
      recoil: "-5",
      effDist: "392",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "2",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm PRS gs", normalizedName: "545x39mm-prs-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "US",
      damage: "65",
      penValue: "15",
      fragChange: "10%",
      recoil: "-25",
      effDist: "1689",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "3",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm US gs", normalizedName: "545x39mm-us-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "T (Tracer)",
      damage: "57",
      penValue: "20",
      fragChange: "16%",
      recoil: "-5",
      effDist: "331",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm T gs", normalizedName: "545x39mm-t-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ",
      damage: "56",
      penValue: "21",
      fragChange: "25%",
      recoil: "",
      effDist: "400",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm FMJ", normalizedName: "545x39mm-fmj" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PS",
      damage: "50",
      penValue: "27",
      fragChange: "40%",
      recoil: "",
      effDist: "352",
      maxHsDist: "466",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "0",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm PS gs", normalizedName: "545x39mm-ps-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PP",
      damage: "48",
      penValue: "33",
      fragChange: "17%",
      recoil: "",
      effDist: "382",
      maxHsDist: "420",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "2",
      class6: "0",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm PP gs", normalizedName: "545x39mm-pp-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BP",
      damage: "49",
      penValue: "35",
      fragChange: "16%",
      recoil: "",
      effDist: "378",
      maxHsDist: "455",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "1",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm BP gs", normalizedName: "545x39mm-bp-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BT (Tracer)",
      damage: "44",
      penValue: "37",
      fragChange: "16%",
      recoil: "3",
      effDist: "310",
      maxHsDist: "252",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm BT gs", normalizedName: "545x39mm-bt-gs" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "7n40",
      damage: "52",
      penValue: "44",
      fragChange: "2%",
      recoil: "-20",
      effDist: "388",
      maxHsDist: "633",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm 7N40", normalizedName: "545x39mm-7n40" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "BS",
      damage: "40",
      penValue: "51",
      fragChange: "17%",
      recoil: "10",
      effDist: "363",
      maxHsDist: "179",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.45x39 mm",
      standard: { name: "5.45x39mm BS gs", normalizedName: "545x39mm-bs-gs" },
      notAvailableOnFleaMarket: true
    },
    {
      name: 'PPBS "Igolnik"',
      damage: "37",
      penValue: "62",
      fragChange: "2%",
      recoil: "15",
      effDist: "430",
      maxHsDist: "85",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "5.45x39 mm",
      standard: {
        name: '5.45x39mm PPBS gs \\"Igolnik\\"',
        normalizedName: "545x39mm-ppbs-gs-igolnik"
      },
      notAvailableOnFleaMarket: true
    }
  ],
  "5.56x45 mm": [
    {
      name: "Warmageddon",
      damage: "85",
      penValue: "3",
      fragChange: "90%",
      recoil: "10",
      effDist: "525",
      maxHsDist: ">1KM",
      class1: "1",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: {
        name: "5.56x45mm Warmageddon",
        normalizedName: "556x45mm-warmageddon"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "HP",
      damage: "75",
      penValue: "9",
      fragChange: "70%",
      recoil: "",
      effDist: "327",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm HP", normalizedName: "556x45mm-hp" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "MK 255 Mod 0",
      damage: "60",
      penValue: "17",
      fragChange: "3%",
      recoil: "",
      effDist: "525",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: {
        name: "5.56x45mm MK 255 Mod 0 (RRLP)",
        normalizedName: "556x45mm-mk-255-mod-0-rrlp"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "Mk318 SOST",
      damage: "67",
      penValue: "20",
      fragChange: "15%",
      recoil: "",
      effDist: "409",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "2",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: {
        name: "5.56x45mm MK 318 Mod 0 (SOST)",
        normalizedName: "556x45mm-mk-318-mod-0-sost"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M856 (Tracer)",
      damage: "55",
      penValue: "23",
      fragChange: "33%",
      recoil: "-2",
      effDist: "358",
      maxHsDist: "975",
      class1: "6",
      class2: "6",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm M856", normalizedName: "556x45mm-m856" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ",
      damage: "52",
      penValue: "24",
      fragChange: "50%",
      recoil: "-5",
      effDist: "399",
      maxHsDist: "618",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "1",
      class5: "0",
      class6: "0",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm FMJ", normalizedName: "556x45mm-fmj" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M855",
      damage: "50",
      penValue: "28",
      fragChange: "40%",
      recoil: "",
      effDist: "358",
      maxHsDist: "464",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm M855", normalizedName: "556x45mm-m855" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M856A1 (Tracer)",
      damage: "51",
      penValue: "37",
      fragChange: "33%",
      recoil: "4",
      effDist: "424",
      maxHsDist: "594",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "3",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm M856A1", normalizedName: "556x45mm-m856a1" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "M855A1",
      damage: "46",
      penValue: "45",
      fragChange: "34%",
      recoil: "5",
      effDist: "366",
      maxHsDist: "352",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm M855A1", normalizedName: "556x45mm-m855a1" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "M995",
      damage: "40",
      penValue: "53",
      fragChange: "32%",
      recoil: "8",
      effDist: "325",
      maxHsDist: "149",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm M995", normalizedName: "556x45mm-m995" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "SSA AP",
      damage: "36",
      penValue: "56",
      fragChange: "20%",
      recoil: "6",
      effDist: "325",
      maxHsDist: "29",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "5.56x45 mm",
      standard: { name: "5.56x45mm SSA AP", normalizedName: "556x45mm-ssa-ap" },
      notAvailableOnFleaMarket: true
    }
  ],
  "7.62x39 mm": [
    {
      name: "HP",
      damage: "87",
      penValue: "15",
      fragChange: "26%",
      recoil: "",
      effDist: "382",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "1",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "7.62x39 mm",
      standard: { name: "7.62x39mm HP", normalizedName: "762x39mm-hp" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "US",
      damage: "56",
      penValue: "29",
      fragChange: "8%",
      recoil: "-30",
      effDist: "1811",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "7.62x39 mm",
      standard: { name: "7.62x39mm US gzh", normalizedName: "762x39mm-us-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "T45M1",
      damage: "62",
      penValue: "30",
      fragChange: "12%",
      recoil: "-6",
      effDist: "314",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "3",
      class5: "1",
      class6: "0",
      category: "7.62x39 mm",
      standard: {
        name: "7.62x39mm T-45M1 gzh",
        normalizedName: "762x39mm-t-45m1-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PS",
      damage: "57",
      penValue: "32",
      fragChange: "25%",
      recoil: "",
      effDist: "393",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "4",
      class5: "3",
      class6: "2",
      category: "7.62x39 mm",
      standard: { name: "7.62x39mm PS gzh", normalizedName: "762x39mm-ps-gzh" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BP",
      damage: "58",
      penValue: "47",
      fragChange: "12%",
      recoil: "5",
      effDist: "387",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "7.62x39 mm",
      standard: { name: "7.62x39mm BP gzh", normalizedName: "762x39mm-bp-gzh" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "MAI AP",
      damage: "47",
      penValue: "58",
      fragChange: "5%",
      recoil: "10",
      effDist: "387",
      maxHsDist: "405",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "5",
      category: "7.62x39 mm",
      standard: { name: "7.62x39mm MAI AP", normalizedName: "762x39mm-mai-ap" },
      notAvailableOnFleaMarket: true
    }
  ],
  ".300 blk": [
    {
      name: "Whisper",
      damage: "90",
      penValue: "14",
      fragChange: "35%",
      recoil: "-5",
      effDist: "490",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "2",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".300 blk",
      standard: {
        name: ".300 Blackout Whisper",
        normalizedName: "300-blackout-whisper"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "VMAX",
      damage: "72",
      penValue: "20",
      fragChange: "25%",
      recoil: "-10",
      effDist: "466",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "4",
      class4: "3",
      class5: "1",
      class6: "0",
      category: ".300 blk",
      standard: {
        name: ".300 Blackout V-Max",
        normalizedName: "300-blackout-v-max"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BCP FMJ",
      damage: "60",
      penValue: "29",
      fragChange: "30%",
      recoil: "",
      effDist: "563",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "3",
      class5: "2",
      class6: "0",
      category: ".300 blk",
      standard: {
        name: ".300 Blackout BCP FMJ",
        normalizedName: "300-blackout-bcp-fmj"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M62 (Tracer)",
      damage: "54",
      penValue: "34",
      fragChange: "0.2",
      recoil: "5",
      effDist: "1039",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".300 blk",
      standard: {
        name: ".300 Blackout M62 Tracer",
        normalizedName: "300-blackout-m62-tracer"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "AP",
      damage: "51",
      penValue: "45",
      fragChange: "30%",
      recoil: "10",
      effDist: "522",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: ".300 blk",
      standard: { name: ".300 Blackout AP", normalizedName: "300-blackout-ap" },
      notAvailableOnFleaMarket: true
    }
  ],
  "7.62x51 mm": [
    {
      name: "Ultra Nosler",
      damage: "107",
      penValue: "15",
      fragChange: "70%",
      recoil: "-5",
      effDist: "536",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "4",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "7.62x51 mm",
      standard: {
        name: "7.62x51mm Ultra Nosler",
        normalizedName: "762x51mm-ultra-nosler"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ",
      damage: "88",
      penValue: "31",
      fragChange: "25%",
      recoil: "-3",
      effDist: "584",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "2",
      class5: "0",
      class6: "0",
      note: "",
      secondNote: "Previously BPZ",
      category: "7.62x51 mm",
      standard: {
        name: "7.62x51mm BCP FMJ",
        normalizedName: "762x51mm-bcp-fmj"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "SP",
      damage: "60",
      penValue: "36",
      fragChange: "20%",
      recoil: "-5",
      effDist: "543",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "2",
      class6: "0",
      note: "",
      secondNote: "Previously TPZ",
      category: "7.62x51 mm",
      standard: { name: "7.62x51mm TCW SP", normalizedName: "762x51mm-tcw-sp" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M80",
      damage: "80",
      penValue: "41",
      fragChange: "17%",
      recoil: "",
      effDist: "483",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "7.62x51 mm",
      standard: { name: "7.62x51mm M80", normalizedName: "762x51mm-m80" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "M62 (Tracer)",
      damage: "79",
      penValue: "44",
      fragChange: "14%",
      recoil: "-5",
      effDist: "462",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      category: "7.62x51 mm",
      standard: {
        name: "7.62x51mm M62 Tracer",
        normalizedName: "762x51mm-m62-tracer"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "M61",
      damage: "70",
      penValue: "64",
      fragChange: "13%",
      recoil: "10",
      effDist: "506",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x51 mm",
      standard: { name: "7.62x51mm M61", normalizedName: "762x51mm-m61" },
      notAvailableOnFleaMarket: true
    },
    {
      name: "M993",
      damage: "67",
      penValue: "70",
      fragChange: "13%",
      recoil: "8",
      effDist: "445",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x51 mm",
      standard: { name: "7.62x51mm M993", normalizedName: "762x51mm-m993" },
      notAvailableOnFleaMarket: true
    }
  ],
  "7.62x54R": [
    {
      name: "T-46M (Tracer)",
      damage: "82",
      penValue: "41",
      fragChange: "18%",
      recoil: "-5",
      effDist: "406",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R T-46M gzh",
        normalizedName: "762x54mm-r-t-46m-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "LPS Gzh",
      damage: "81",
      penValue: "42",
      fragChange: "18%",
      recoil: "",
      effDist: "492",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "4",
      class6: "3",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R LPS gzh",
        normalizedName: "762x54mm-r-lps-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "PS",
      damage: "86",
      penValue: "45",
      fragChange: "8%",
      recoil: "8",
      effDist: "510",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      note: "",
      secondNote: "Previously 7n1",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R PS gzh",
        normalizedName: "762x54mm-r-ps-gzh"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "BT (Tracer)",
      damage: "78",
      penValue: "59",
      fragChange: "8%",
      recoil: "-4",
      effDist: "491",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7BT1",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R BT gzh",
        normalizedName: "762x54mm-r-bt-gzh"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "SNB",
      damage: "75",
      penValue: "62",
      fragChange: "8%",
      recoil: "10",
      effDist: "510",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R SNB gzh",
        normalizedName: "762x54mm-r-snb-gzh"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "BS",
      damage: "72",
      penValue: "70",
      fragChange: "8%",
      recoil: "",
      effDist: "597",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      note: "",
      secondNote: "Previously 7n37",
      category: "7.62x54R",
      standard: {
        name: "7.62x54mm R BS gs",
        normalizedName: "762x54mm-r-bs-gs"
      },
      notAvailableOnFleaMarket: true
    }
  ],
  "12.7x55 mm": [
    {
      name: "ps12a",
      damage: "165",
      penValue: "10",
      fragChange: "70%",
      recoil: "-12",
      effDist: "439",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      category: "12.7x55 mm",
      standard: { name: "12.7x55mm PS12A", normalizedName: "127x55mm-ps12a" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ps12",
      damage: "115",
      penValue: "28",
      fragChange: "30%",
      recoil: "",
      effDist: "2076",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "5",
      class4: "2",
      class5: "1",
      class6: "0",
      category: "12.7x55 mm",
      standard: { name: "12.7x55mm PS12", normalizedName: "127x55mm-ps12" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "ps12b",
      damage: "102",
      penValue: "46",
      fragChange: "30%",
      recoil: "15",
      effDist: "719",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "4",
      category: "12.7x55 mm",
      standard: { name: "12.7x55mm PS12B", normalizedName: "127x55mm-ps12b" },
      notAvailableOnFleaMarket: false
    }
  ],
  ".338 Lapua Magnum": [
    {
      name: "Tac-X",
      damage: "196",
      penValue: "18",
      fragChange: "50%",
      recoil: "5",
      effDist: "716",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "5",
      class3: "3",
      class4: "1",
      class5: "0",
      class6: "0",
      category: ".338 Lapua Magnum",
      standard: {
        name: ".338 Lapua Magnum TAC-X",
        normalizedName: "338-lapua-magnum-tac-x"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "UPZ",
      damage: "142",
      penValue: "32",
      fragChange: "60%",
      recoil: "",
      effDist: "702",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "5",
      class5: "4",
      class6: "2",
      category: ".338 Lapua Magnum",
      standard: {
        name: ".338 Lapua Magnum UCW",
        normalizedName: "338-lapua-magnum-ucw"
      },
      notAvailableOnFleaMarket: false
    },
    {
      name: "FMJ",
      damage: "122",
      penValue: "47",
      fragChange: "20%",
      recoil: "",
      effDist: "733",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "5",
      class6: "5",
      category: ".338 Lapua Magnum",
      standard: {
        name: ".338 Lapua Magnum FMJ",
        normalizedName: "338-lapua-magnum-fmj"
      },
      notAvailableOnFleaMarket: true
    },
    {
      name: "AP",
      damage: "115",
      penValue: "79",
      fragChange: "13%",
      recoil: "10",
      effDist: "696",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: ".338 Lapua Magnum",
      standard: {
        name: ".338 Lapua Magnum AP",
        normalizedName: "338-lapua-magnum-ap"
      },
      notAvailableOnFleaMarket: true
    }
  ],
  "Mounted Weapons": [
    {
      name: "30mm Grenade",
      damage: "199",
      penValue: "1",
      fragChange: "0%",
      recoil: "",
      effDist: "",
      maxHsDist: "",
      class1: "0",
      class2: "0",
      class3: "0",
      class4: "0",
      class5: "0",
      class6: "0",
      note: "This has an explosion radius like grenades which does most (all) of the damage",
      category: "Mounted Weapons",
      standard: { name: "", normalizedName: "" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "12.7x108mm",
      damage: "182",
      penValue: "88",
      fragChange: "17%",
      recoil: "",
      effDist: "891",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "Mounted Weapons",
      standard: { name: "", normalizedName: "" },
      notAvailableOnFleaMarket: false
    },
    {
      name: "12.7x108mm Tracer",
      damage: "199",
      penValue: "80",
      fragChange: "17%",
      recoil: "",
      effDist: "446",
      maxHsDist: ">1KM",
      class1: "6",
      class2: "6",
      class3: "6",
      class4: "6",
      class5: "6",
      class6: "6",
      category: "Mounted Weapons",
      standard: { name: "", normalizedName: "" },
      notAvailableOnFleaMarket: false
    }
  ],
  Other: [
    {
      name: "40mm Buckshot Grenade",
      damage: "160",
      penValue: "5",
      fragChange: "0%",
      recoil: "",
      effDist: "994",
      maxHsDist: ">1KM",
      class1: "5",
      class2: "3",
      class3: "3",
      class4: "3",
      class5: "3",
      class6: "3",
      note: "15 Pellets",
      category: "Other",
      standard: { name: "", normalizedName: "" },
      notAvailableOnFleaMarket: false
    }
  ]
};

export default fallback;
